## Import Modules

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import os

In [2]:
%matplotlib inline   

## Data Gathering 

In [3]:
path = r'C:\Users\ACER\Documents\ML_Cats_Dogs\train\train'

In [4]:
l=os.listdir(path)

In [5]:
data=[]

for img in l:
    img_path=os.path.join(path,img)
    arr=cv2.imread(img_path,1)
    arr=cv2.cvtColor(arr,cv2.COLOR_BGR2RGB)
    arr_new=cv2.resize(arr,(100,100))
    img1=img.split('.')
    if(img1[0]=='cat'):
        label=0
    else:
        label=1
    data.append([arr_new, label])

In [6]:
data

[[array([[[204, 165,  88],
          [210, 171,  94],
          [213, 174,  97],
          ...,
          [246, 209, 128],
          [246, 205, 123],
          [241, 202, 123]],
  
         [[204, 165,  88],
          [210, 171,  94],
          [213, 174,  97],
          ...,
          [247, 212, 131],
          [245, 207, 126],
          [242, 203, 124]],
  
         [[204, 165,  88],
          [210, 171,  94],
          [213, 174,  97],
          ...,
          [248, 215, 138],
          [245, 208, 128],
          [244, 205, 126]],
  
         ...,
  
         [[159, 125,  54],
          [161, 127,  56],
          [164, 130,  59],
          ...,
          [  3,   4,   0],
          [  3,   4,   0],
          [  2,   2,   0]],
  
         [[155, 124,  56],
          [157, 126,  59],
          [160, 129,  61],
          ...,
          [  3,   3,   1],
          [  3,   3,   1],
          [  3,   3,   1]],
  
         [[152, 121,  54],
          [154, 123,  56],
          [158, 127,  60

## Shuffling the continuous arrangement data of cats and dogs

In [7]:
import random
random.shuffle(data)

In [8]:
x=[]
y=[]

In [9]:
for features, label in data:
    x.append(features)
    y.append(label)

In [10]:
x=np.array(x)
y=np.array(y)

In [11]:
x

array([[[[ 51,  69,  45],
         [ 57,  69,  81],
         [ 60,  81,  75],
         ...,
         [113, 135, 148],
         [112, 134, 146],
         [110, 132, 145]],

        [[116, 118,  93],
         [ 66,  80,  81],
         [ 61,  82,  82],
         ...,
         [118, 140, 153],
         [116, 138, 151],
         [113, 135, 148]],

        [[190, 172, 142],
         [ 63,  76,  66],
         [ 60,  81,  86],
         ...,
         [117, 139, 152],
         [117, 139, 152],
         [117, 139, 152]],

        ...,

        [[109,  67,  43],
         [106,  64,  41],
         [110,  68,  44],
         ...,
         [128,  93,  71],
         [137, 102,  80],
         [136, 101,  79]],

        [[104,  62,  38],
         [109,  67,  43],
         [110,  68,  44],
         ...,
         [134,  99,  77],
         [138, 103,  81],
         [142, 107,  85]],

        [[105,  63,  39],
         [107,  65,  41],
         [104,  62,  38],
         ...,
         [135, 104,  76],
        

In [12]:
y

array([0, 1, 0, ..., 1, 1, 0])

In [13]:
x=x/255  #Now all pixelvalues lie from 0 to 255, on dividing by 255 makes the value smaller and the process fast

In [14]:
x

array([[[[0.2       , 0.27058824, 0.17647059],
         [0.22352941, 0.27058824, 0.31764706],
         [0.23529412, 0.31764706, 0.29411765],
         ...,
         [0.44313725, 0.52941176, 0.58039216],
         [0.43921569, 0.5254902 , 0.57254902],
         [0.43137255, 0.51764706, 0.56862745]],

        [[0.45490196, 0.4627451 , 0.36470588],
         [0.25882353, 0.31372549, 0.31764706],
         [0.23921569, 0.32156863, 0.32156863],
         ...,
         [0.4627451 , 0.54901961, 0.6       ],
         [0.45490196, 0.54117647, 0.59215686],
         [0.44313725, 0.52941176, 0.58039216]],

        [[0.74509804, 0.6745098 , 0.55686275],
         [0.24705882, 0.29803922, 0.25882353],
         [0.23529412, 0.31764706, 0.3372549 ],
         ...,
         [0.45882353, 0.54509804, 0.59607843],
         [0.45882353, 0.54509804, 0.59607843],
         [0.45882353, 0.54509804, 0.59607843]],

        ...,

        [[0.42745098, 0.2627451 , 0.16862745],
         [0.41568627, 0.25098039, 0.16078431]

In [15]:
x.shape   #(no of images, length, breadth, no of channels-red,green and blue channels)

(25000, 100, 100, 3)

## Train model

In [16]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

model = Sequential()

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, input_shape = x.shape[1:], activation = 'relu'))

model.add(Dense(2, activation = 'softmax'))  #Can use sigmoid function also because they both restrict the value from 0 to 1

In [17]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [18]:
model.fit(x, y, epochs=5, validation_split=0.1)

Epoch 1/5
704/704 [==============================] - 3945s 6s/step - loss: 0.6067 - accuracy: 0.6720 - val_loss: 0.4945 - val_accuracy: 0.7688
Epoch 2/5
704/704 [==============================] - 3712s 5s/step - loss: 0.4746 - accuracy: 0.7750 - val_loss: 0.4723 - val_accuracy: 0.7804
Epoch 3/5
704/704 [==============================] - 3288s 5s/step - loss: 0.3914 - accuracy: 0.8256 - val_loss: 0.4365 - val_accuracy: 0.7984
Epoch 4/5
704/704 [==============================] - 2900s 4s/step - loss: 0.3011 - accuracy: 0.8676 - val_loss: 0.4597 - val_accuracy: 0.8076
Epoch 5/5
704/704 [==============================] - 2955s 4s/step - loss: 0.1863 - accuracy: 0.9236 - val_loss: 0.5878 - val_accuracy: 0.8032


In [20]:
import tensorflow.python.util.deprecation as deprecation
deprecation._PRINT_DEPRECATION_WARNINGS = False

In [21]:
model.save('3x3x64-catvsdog.model')

INFO:tensorflow:Assets written to: 3x3x64-catvsdog.model\assets
